[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
